(function() {var implementors = {};
implementors['ordered_iter'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;A: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>, B: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ordered_iter/struct.InnerJoinMap.html' title='ordered_iter::InnerJoinMap'>InnerJoinMap</a>&lt;A, B&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;A: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>, B: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ordered_iter/struct.InnerJoinMapSet.html' title='ordered_iter::InnerJoinMapSet'>InnerJoinMapSet</a>&lt;A, B&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;A: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>, B: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ordered_iter/struct.InnerJoinSet.html' title='ordered_iter::InnerJoinSet'>InnerJoinSet</a>&lt;A, B&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;A, B&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ordered_iter/struct.OuterJoin.html' title='ordered_iter::OuterJoin'>OuterJoin</a>&lt;A, B&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
